### PR TITLE
Update continuous deployment workflow

### PR DESCRIPTION
**Pull request by Ndpnt**

### CODE REVIEW

**Review by martinratinaud — APPROVED** [review]
Didn't we need the SSH key also.
If yes, please add a comment in the PR

**Review by MattiSG — APPROVED** [review]

**Review by MattiSG — CHANGES_REQUESTED** [review]
Have you checked what I wrote in https://github.com/OpenTermsArchive/services-dating/pull/38?

**Comment by Ndpnt** [comment]
So, why do you request changes?

**Comment by MattiSG** [comment]
Because this PR depends on a branch that will be removed, see https://github.com/OpenTermsArchive/services-dating/pull/38/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L10.

**Comment by Ndpnt** [comment]
Already done in #38

**Pull request closed without merging**
